import { Navigation } from "@/components/Navigation";

import { ThemeProvider } from "@/components/ThemeProvider";
import { Toaster } from "@/ui/sonner";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default async function RootLayout({ children }: RootLayoutProps) {
  return (
    <ThemeProvider>
      <html key="root" suppressHydrationWarning>
        <body
          id="body"
          key="body"
          className={`${geistSans.variable} ${geistMono.variable} relative antialiased`}
        >
          <Navigation key="nav" />
          {children}
          <Toaster key="toaster" />
        </body>
      </html>
    </ThemeProvider>
  );
}
